-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lms_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    x_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    x_in_TVALID : IN STD_LOGIC;
    x_in_TREADY : OUT STD_LOGIC;
    x_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    x_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    x_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    d_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    d_in_TVALID : IN STD_LOGIC;
    d_in_TREADY : OUT STD_LOGIC;
    d_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    d_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    d_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    e_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    e_out_TVALID : OUT STD_LOGIC;
    e_out_TREADY : IN STD_LOGIC;
    e_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    e_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    e_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    y_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_out_TVALID : OUT STD_LOGIC;
    y_out_TREADY : IN STD_LOGIC;
    y_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of lms_filter is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "lms_filter_lms_filter,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=46.744000,HLS_SYN_LAT=31,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1354,HLS_SYN_LUT=2140,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_3C000000 : STD_LOGIC_VECTOR (31 downto 0) := "00111100000000000000000000000000";
    constant ap_const_lv32_3C23D70A : STD_LOGIC_VECTOR (31 downto 0) := "00111100001000111101011100001010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal ap_rst_n_inv : STD_LOGIC;
    signal x_buf_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_buf_ce0 : STD_LOGIC;
    signal x_buf_we0 : STD_LOGIC;
    signal x_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_buf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_buf_ce1 : STD_LOGIC;
    signal x_buf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal weights_ce0 : STD_LOGIC;
    signal weights_we0 : STD_LOGIC;
    signal weights_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_ce1 : STD_LOGIC;
    signal weights_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_nbreadreq_fu_104_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_nbreadreq_fu_118_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_in_TDATA_blk_n : STD_LOGIC;
    signal e_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal y_out_TDATA_blk_n : STD_LOGIC;
    signal grp_fu_226_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_235 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal tmp_reg_339 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln29_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln29_reg_347 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_272_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln29_reg_352 : STD_LOGIC_VECTOR (6 downto 0);
    signal bit_sel1_reg_357 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln30_fu_284_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln30_reg_362 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln60_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln60_reg_367 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln29_fu_300_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal xor_ln30_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln30_fu_316_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_232_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv3_reg_388 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal conv8_reg_393 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_222_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal e_reg_401 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_idle : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_ready : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_we0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce1 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_idle : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_ready : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out_ap_vld : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_ce0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_ce0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_ce : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_done : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_idle : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_ready : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_ce0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_we0 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce1 : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_ce : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_ce : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg : STD_LOGIC := '0';
    signal ap_predicate_op57_read_state1 : BOOLEAN;
    signal ap_predicate_op60_read_state1 : BOOLEAN;
    signal ap_block_state1_ignore_call6 : BOOLEAN;
    signal x_buf_we0_out : STD_LOGIC;
    signal grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state20 : BOOLEAN;
    signal x_buf_we0_local : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal x_buf_ce0_local : STD_LOGIC;
    signal grp_fu_222_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_226_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_226_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_232_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bit_sel_fu_258_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln_fu_294_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln1_fu_310_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_222_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_222_ce : STD_LOGIC;
    signal grp_fu_226_ce : STD_LOGIC;
    signal ap_block_state21 : BOOLEAN;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_fu_232_ce : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_417_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal regslice_both_e_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state25 : BOOLEAN;
    signal ap_predicate_op116_call_state25 : BOOLEAN;
    signal ap_block_state25_on_subcall_done : BOOLEAN;
    signal regslice_both_x_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal x_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal x_in_TVALID_int_regslice : STD_LOGIC;
    signal x_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_x_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal x_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal x_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal x_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal d_in_TVALID_int_regslice : STD_LOGIC;
    signal d_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_d_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_d_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_d_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_d_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_last_V_U_ack_in : STD_LOGIC;
    signal e_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal e_out_TVALID_int_regslice : STD_LOGIC;
    signal e_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_e_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_e_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_e_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_e_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_e_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_e_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_e_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_e_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_e_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_e_out_V_last_V_U_vld_out : STD_LOGIC;
    signal y_out_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal y_out_TVALID_int_regslice : STD_LOGIC;
    signal y_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lms_filter_lms_filter_Pipeline_VITIS_LOOP_33_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_buf_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_buf_ce0 : OUT STD_LOGIC;
        x_buf_we0 : OUT STD_LOGIC;
        x_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        x_buf_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_buf_ce1 : OUT STD_LOGIC;
        x_buf_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lms_filter_lms_filter_Pipeline_VITIS_LOOP_41_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add255_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add255_out_ap_vld : OUT STD_LOGIC;
        weights_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        weights_ce0 : OUT STD_LOGIC;
        weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_buf_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_buf_ce0 : OUT STD_LOGIC;
        x_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_ce : OUT STD_LOGIC );
    end component;


    component lms_filter_lms_filter_Pipeline_VITIS_LOOP_49_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mul1 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_buf_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_buf_ce0 : OUT STD_LOGIC;
        x_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        weights_ce0 : OUT STD_LOGIC;
        weights_we0 : OUT STD_LOGIC;
        weights_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        weights_ce1 : OUT STD_LOGIC;
        weights_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_222_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_222_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_222_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_222_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_222_p_ce : OUT STD_LOGIC;
        grp_fu_417_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_417_p_ce : OUT STD_LOGIC );
    end component;


    component lms_filter_faddfsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lms_filter_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lms_filter_sitofp_32s_32_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lms_filter_x_buf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lms_filter_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    x_buf_U : component lms_filter_x_buf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_buf_address0,
        ce0 => x_buf_ce0,
        we0 => x_buf_we0,
        d0 => x_buf_d0,
        q0 => x_buf_q0,
        address1 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address1,
        ce1 => x_buf_ce1,
        q1 => x_buf_q1);

    weights_U : component lms_filter_x_buf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => weights_address0,
        ce0 => weights_ce0,
        we0 => weights_we0,
        d0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_d0,
        q0 => weights_q0,
        address1 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address1,
        ce1 => weights_ce1,
        q1 => weights_q1);

    grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198 : component lms_filter_lms_filter_Pipeline_VITIS_LOOP_33_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start,
        ap_done => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done,
        ap_idle => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_idle,
        ap_ready => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_ready,
        x_buf_address0 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address0,
        x_buf_ce0 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce0,
        x_buf_we0 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_we0,
        x_buf_d0 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_d0,
        x_buf_address1 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address1,
        x_buf_ce1 => grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce1,
        x_buf_q1 => x_buf_q1);

    grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204 : component lms_filter_lms_filter_Pipeline_VITIS_LOOP_41_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start,
        ap_done => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done,
        ap_idle => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_idle,
        ap_ready => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_ready,
        add255_out => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out,
        add255_out_ap_vld => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out_ap_vld,
        weights_address0 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_address0,
        weights_ce0 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_ce0,
        weights_q0 => weights_q0,
        x_buf_address0 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_address0,
        x_buf_ce0 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_ce0,
        x_buf_q0 => x_buf_q0,
        grp_fu_417_p_din0 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din0,
        grp_fu_417_p_din1 => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din1,
        grp_fu_417_p_dout0 => grp_fu_417_p2,
        grp_fu_417_p_ce => grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_ce);

    grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213 : component lms_filter_lms_filter_Pipeline_VITIS_LOOP_49_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start,
        ap_done => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_done,
        ap_idle => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_idle,
        ap_ready => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_ready,
        mul1 => reg_235,
        x_buf_address0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_address0,
        x_buf_ce0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_ce0,
        x_buf_q0 => x_buf_q0,
        weights_address0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address0,
        weights_ce0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce0,
        weights_we0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_we0,
        weights_d0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_d0,
        weights_address1 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address1,
        weights_ce1 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce1,
        weights_q1 => weights_q1,
        grp_fu_222_p_din0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din0,
        grp_fu_222_p_din1 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din1,
        grp_fu_222_p_opcode => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_opcode,
        grp_fu_222_p_dout0 => grp_fu_222_p2,
        grp_fu_222_p_ce => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_ce,
        grp_fu_417_p_din0 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din0,
        grp_fu_417_p_din1 => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din1,
        grp_fu_417_p_dout0 => grp_fu_417_p2,
        grp_fu_417_p_ce => grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_ce);

    faddfsub_32ns_32ns_32_5_full_dsp_1_U13 : component lms_filter_faddfsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_222_p0,
        din1 => grp_fu_222_p1,
        opcode => grp_fu_222_opcode,
        ce => grp_fu_222_ce,
        dout => grp_fu_222_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U14 : component lms_filter_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_226_p0,
        din1 => grp_fu_226_p1,
        ce => grp_fu_226_ce,
        dout => grp_fu_226_p2);

    sitofp_32s_32_6_no_dsp_1_U15 : component lms_filter_sitofp_32s_32_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_232_p0,
        ce => grp_fu_232_ce,
        dout => grp_fu_232_p1);

    fmul_32ns_32ns_32_4_max_dsp_1_U16 : component lms_filter_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_417_p0,
        din1 => grp_fu_417_p1,
        ce => grp_fu_417_ce,
        dout => grp_fu_417_p2);

    regslice_both_x_in_V_data_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_in_TDATA,
        vld_in => x_in_TVALID,
        ack_in => regslice_both_x_in_V_data_V_U_ack_in,
        data_out => x_in_TDATA_int_regslice,
        vld_out => x_in_TVALID_int_regslice,
        ack_out => x_in_TREADY_int_regslice,
        apdone_blk => regslice_both_x_in_V_data_V_U_apdone_blk);

    regslice_both_x_in_V_keep_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_in_TKEEP,
        vld_in => x_in_TVALID,
        ack_in => regslice_both_x_in_V_keep_V_U_ack_in,
        data_out => x_in_TKEEP_int_regslice,
        vld_out => regslice_both_x_in_V_keep_V_U_vld_out,
        ack_out => x_in_TREADY_int_regslice,
        apdone_blk => regslice_both_x_in_V_keep_V_U_apdone_blk);

    regslice_both_x_in_V_strb_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_in_TSTRB,
        vld_in => x_in_TVALID,
        ack_in => regslice_both_x_in_V_strb_V_U_ack_in,
        data_out => x_in_TSTRB_int_regslice,
        vld_out => regslice_both_x_in_V_strb_V_U_vld_out,
        ack_out => x_in_TREADY_int_regslice,
        apdone_blk => regslice_both_x_in_V_strb_V_U_apdone_blk);

    regslice_both_x_in_V_last_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_in_TLAST,
        vld_in => x_in_TVALID,
        ack_in => regslice_both_x_in_V_last_V_U_ack_in,
        data_out => x_in_TLAST_int_regslice,
        vld_out => regslice_both_x_in_V_last_V_U_vld_out,
        ack_out => x_in_TREADY_int_regslice,
        apdone_blk => regslice_both_x_in_V_last_V_U_apdone_blk);

    regslice_both_d_in_V_data_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TDATA,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_data_V_U_ack_in,
        data_out => d_in_TDATA_int_regslice,
        vld_out => d_in_TVALID_int_regslice,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_data_V_U_apdone_blk);

    regslice_both_d_in_V_keep_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TKEEP,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_keep_V_U_ack_in,
        data_out => d_in_TKEEP_int_regslice,
        vld_out => regslice_both_d_in_V_keep_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_keep_V_U_apdone_blk);

    regslice_both_d_in_V_strb_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TSTRB,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_strb_V_U_ack_in,
        data_out => d_in_TSTRB_int_regslice,
        vld_out => regslice_both_d_in_V_strb_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_strb_V_U_apdone_blk);

    regslice_both_d_in_V_last_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TLAST,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_last_V_U_ack_in,
        data_out => d_in_TLAST_int_regslice,
        vld_out => regslice_both_d_in_V_last_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_last_V_U_apdone_blk);

    regslice_both_e_out_V_data_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => e_out_TDATA_int_regslice,
        vld_in => e_out_TVALID_int_regslice,
        ack_in => e_out_TREADY_int_regslice,
        data_out => e_out_TDATA,
        vld_out => regslice_both_e_out_V_data_V_U_vld_out,
        ack_out => e_out_TREADY,
        apdone_blk => regslice_both_e_out_V_data_V_U_apdone_blk);

    regslice_both_e_out_V_keep_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => e_out_TVALID_int_regslice,
        ack_in => regslice_both_e_out_V_keep_V_U_ack_in_dummy,
        data_out => e_out_TKEEP,
        vld_out => regslice_both_e_out_V_keep_V_U_vld_out,
        ack_out => e_out_TREADY,
        apdone_blk => regslice_both_e_out_V_keep_V_U_apdone_blk);

    regslice_both_e_out_V_strb_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => e_out_TVALID_int_regslice,
        ack_in => regslice_both_e_out_V_strb_V_U_ack_in_dummy,
        data_out => e_out_TSTRB,
        vld_out => regslice_both_e_out_V_strb_V_U_vld_out,
        ack_out => e_out_TREADY,
        apdone_blk => regslice_both_e_out_V_strb_V_U_apdone_blk);

    regslice_both_e_out_V_last_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => or_ln60_reg_367,
        vld_in => e_out_TVALID_int_regslice,
        ack_in => regslice_both_e_out_V_last_V_U_ack_in_dummy,
        data_out => e_out_TLAST,
        vld_out => regslice_both_e_out_V_last_V_U_vld_out,
        ack_out => e_out_TREADY,
        apdone_blk => regslice_both_e_out_V_last_V_U_apdone_blk);

    regslice_both_y_out_V_data_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_out_TDATA_int_regslice,
        vld_in => y_out_TVALID_int_regslice,
        ack_in => y_out_TREADY_int_regslice,
        data_out => y_out_TDATA,
        vld_out => regslice_both_y_out_V_data_V_U_vld_out,
        ack_out => y_out_TREADY,
        apdone_blk => regslice_both_y_out_V_data_V_U_apdone_blk);

    regslice_both_y_out_V_keep_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => y_out_TVALID_int_regslice,
        ack_in => regslice_both_y_out_V_keep_V_U_ack_in_dummy,
        data_out => y_out_TKEEP,
        vld_out => regslice_both_y_out_V_keep_V_U_vld_out,
        ack_out => y_out_TREADY,
        apdone_blk => regslice_both_y_out_V_keep_V_U_apdone_blk);

    regslice_both_y_out_V_strb_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => y_out_TVALID_int_regslice,
        ack_in => regslice_both_y_out_V_strb_V_U_ack_in_dummy,
        data_out => y_out_TSTRB,
        vld_out => regslice_both_y_out_V_strb_V_U_vld_out,
        ack_out => y_out_TREADY,
        apdone_blk => regslice_both_y_out_V_strb_V_U_apdone_blk);

    regslice_both_y_out_V_last_V_U : component lms_filter_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => or_ln60_reg_367,
        vld_in => y_out_TVALID_int_regslice,
        ack_in => regslice_both_y_out_V_last_V_U_ack_in_dummy,
        data_out => y_out_TLAST,
        vld_out => regslice_both_y_out_V_last_V_U_vld_out,
        ack_out => y_out_TREADY,
        apdone_blk => regslice_both_y_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg <= ap_const_logic_0;
            else
                if (((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_ignore_call6) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_ready = ap_const_logic_1)) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_ready = ap_const_logic_1)) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_ready = ap_const_logic_1)) then 
                    grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                bit_sel1_reg_357 <= d_in_TDATA_int_regslice(7 downto 7);
                or_ln60_reg_367 <= or_ln60_fu_288_p2;
                tmp_1_reg_343 <= tmp_1_nbreadreq_fu_118_p6;
                tmp_reg_339 <= tmp_nbreadreq_fu_104_p6;
                trunc_ln29_reg_352 <= trunc_ln29_fu_272_p1;
                trunc_ln30_reg_362 <= trunc_ln30_fu_284_p1;
                xor_ln29_reg_347 <= xor_ln29_fu_266_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                conv3_reg_388 <= grp_fu_232_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                conv8_reg_393 <= grp_fu_232_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                e_reg_401 <= grp_fu_222_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state11))) then
                reg_235 <= grp_fu_226_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                xor_ln30_reg_378 <= xor_ln30_fu_305_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, tmp_nbreadreq_fu_104_p6, tmp_1_nbreadreq_fu_118_p6, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state14, ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done, ap_CS_fsm_state25, ap_block_state1, ap_block_state20, ap_block_state21, ap_block_state25, ap_block_state25_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_0) or (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                if (((ap_const_boolean_0 = ap_block_state21) and (ap_const_logic_1 = ap_CS_fsm_state21))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if ((not(((ap_const_boolean_1 = ap_block_state25_on_subcall_done) or (ap_const_boolean_1 = ap_block_state25))) and (ap_const_logic_1 = ap_CS_fsm_state25))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state25;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done)
    begin
        if ((grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(ap_block_state20)
    begin
        if ((ap_const_boolean_1 = ap_block_state20)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state21_blk_assign_proc : process(ap_block_state21)
    begin
        if ((ap_const_boolean_1 = ap_block_state21)) then 
            ap_ST_fsm_state21_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state21_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;

    ap_ST_fsm_state25_blk_assign_proc : process(ap_block_state25, ap_block_state25_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state25_on_subcall_done) or (ap_const_boolean_1 = ap_block_state25))) then 
            ap_ST_fsm_state25_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state25_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done)
    begin
        if ((grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_predicate_op57_read_state1, ap_predicate_op60_read_state1, x_in_TVALID_int_regslice, d_in_TVALID_int_regslice)
    begin
                ap_block_state1 <= (((d_in_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op60_read_state1 = ap_const_boolean_1)) or ((x_in_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op57_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state1_ignore_call6_assign_proc : process(ap_predicate_op57_read_state1, ap_predicate_op60_read_state1, x_in_TVALID_int_regslice, d_in_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call6 <= (((d_in_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op60_read_state1 = ap_const_boolean_1)) or ((x_in_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op57_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state20_assign_proc : process(e_out_TREADY_int_regslice, y_out_TREADY_int_regslice)
    begin
                ap_block_state20 <= ((y_out_TREADY_int_regslice = ap_const_logic_0) or (e_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state21_assign_proc : process(e_out_TREADY_int_regslice, y_out_TREADY_int_regslice)
    begin
                ap_block_state21 <= ((y_out_TREADY_int_regslice = ap_const_logic_0) or (e_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state25_assign_proc : process(regslice_both_e_out_V_data_V_U_apdone_blk, regslice_both_y_out_V_data_V_U_apdone_blk)
    begin
                ap_block_state25 <= ((regslice_both_y_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_e_out_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state25_on_subcall_done_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_done, ap_predicate_op116_call_state25)
    begin
                ap_block_state25_on_subcall_done <= ((ap_predicate_op116_call_state25 = ap_const_boolean_1) and (grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_done = ap_const_logic_0));
    end process;


    ap_predicate_op116_call_state25_assign_proc : process(tmp_reg_339, tmp_1_reg_343)
    begin
                ap_predicate_op116_call_state25 <= ((tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1));
    end process;


    ap_predicate_op57_read_state1_assign_proc : process(tmp_nbreadreq_fu_104_p6, tmp_1_nbreadreq_fu_118_p6)
    begin
                ap_predicate_op57_read_state1 <= ((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1));
    end process;


    ap_predicate_op60_read_state1_assign_proc : process(tmp_nbreadreq_fu_104_p6, tmp_1_nbreadreq_fu_118_p6)
    begin
                ap_predicate_op60_read_state1 <= ((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bit_sel_fu_258_p3 <= x_in_TDATA_int_regslice(7 downto 7);

    d_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_104_p6, tmp_1_nbreadreq_fu_118_p6, d_in_TVALID_int_regslice)
    begin
        if (((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            d_in_TDATA_blk_n <= d_in_TVALID_int_regslice;
        else 
            d_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    d_in_TREADY <= regslice_both_d_in_V_data_V_U_ack_in;

    d_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_predicate_op60_read_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_predicate_op60_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            d_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            d_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    e_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state21, e_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            e_out_TDATA_blk_n <= e_out_TREADY_int_regslice;
        else 
            e_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    e_out_TDATA_int_regslice <= e_reg_401;
    e_out_TVALID <= regslice_both_e_out_V_data_V_U_vld_out;

    e_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state20, ap_block_state20)
    begin
        if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            e_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            e_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_222_ce_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_ce, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_222_ce <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_ce;
        else 
            grp_fu_222_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_222_opcode_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_opcode, ap_CS_fsm_state25, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_222_opcode <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_opcode),2));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_222_opcode <= ap_const_lv2_1;
        else 
            grp_fu_222_opcode <= "XX";
        end if; 
    end process;


    grp_fu_222_p0_assign_proc : process(reg_235, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din0, ap_CS_fsm_state25, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_222_p0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_222_p0 <= reg_235;
        else 
            grp_fu_222_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_222_p1_assign_proc : process(grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din1, ap_CS_fsm_state25, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_222_p1 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_222_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_222_p1 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out;
        else 
            grp_fu_222_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_226_ce_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state11, ap_CS_fsm_state14, ap_CS_fsm_state23, ap_CS_fsm_state10, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done, ap_CS_fsm_state13, ap_block_state20, ap_CS_fsm_state12, ap_CS_fsm_state8, ap_block_state21, ap_CS_fsm_state9, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_boolean_0 = ap_block_state21) and (ap_const_logic_1 = ap_CS_fsm_state21)) or ((grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20)))) then 
            grp_fu_226_ce <= ap_const_logic_1;
        else 
            grp_fu_226_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_226_p0_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state11, conv3_reg_388, conv8_reg_393, e_reg_401, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_226_p0 <= e_reg_401;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_226_p0 <= conv8_reg_393;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_226_p0 <= conv3_reg_388;
        else 
            grp_fu_226_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_226_p1_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state11, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_226_p1 <= ap_const_lv32_3C23D70A;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            grp_fu_226_p1 <= ap_const_lv32_3C000000;
        else 
            grp_fu_226_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_232_ce_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state10, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_done = ap_const_logic_1)))) then 
            grp_fu_232_ce <= ap_const_logic_1;
        else 
            grp_fu_232_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_232_p0_assign_proc : process(sext_ln29_fu_300_p1, ap_CS_fsm_state2, sext_ln30_fu_316_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_232_p0 <= sext_ln30_fu_316_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_232_p0 <= sext_ln29_fu_300_p1;
        else 
            grp_fu_232_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_417_ce_assign_proc : process(ap_CS_fsm_state14, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_ce, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_ce, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_417_ce <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_417_ce <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_ce;
        else 
            grp_fu_417_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_417_p0_assign_proc : process(ap_CS_fsm_state14, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din0, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din0, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_417_p0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_417_p0 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din0;
        else 
            grp_fu_417_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_417_p1_assign_proc : process(ap_CS_fsm_state14, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din1, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din1, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            grp_fu_417_p1 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_grp_fu_417_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_417_p1 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_grp_fu_417_p_din1;
        else 
            grp_fu_417_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_ap_start_reg;
    grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_ap_start_reg;
    grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_ap_start_reg;
    or_ln60_fu_288_p2 <= (x_in_TLAST_int_regslice or d_in_TLAST_int_regslice);
        sext_ln29_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln_fu_294_p3),32));

        sext_ln30_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xor_ln1_fu_310_p3),32));

    tmp_1_nbreadreq_fu_118_p6 <= (0=>(d_in_TVALID_int_regslice), others=>'-');
    tmp_nbreadreq_fu_104_p6 <= (0=>(x_in_TVALID_int_regslice), others=>'-');
    trunc_ln29_fu_272_p1 <= x_in_TDATA_int_regslice(7 - 1 downto 0);
    trunc_ln30_fu_284_p1 <= d_in_TDATA_int_regslice(7 - 1 downto 0);

    weights_address0_assign_proc : process(ap_CS_fsm_state14, tmp_reg_339, tmp_1_reg_343, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_address0, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address0, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            weights_address0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            weights_address0 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_address0;
        else 
            weights_address0 <= "XXXX";
        end if; 
    end process;


    weights_ce0_assign_proc : process(ap_CS_fsm_state14, tmp_reg_339, tmp_1_reg_343, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_ce0, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce0, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            weights_ce0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            weights_ce0 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_weights_ce0;
        else 
            weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_ce1_assign_proc : process(tmp_reg_339, tmp_1_reg_343, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce1, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            weights_ce1 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_ce1;
        else 
            weights_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_we0_assign_proc : process(tmp_reg_339, tmp_1_reg_343, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_we0, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            weights_we0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_weights_we0;
        else 
            weights_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_buf_address0_assign_proc : process(ap_CS_fsm_state14, tmp_reg_339, tmp_1_reg_343, ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address0, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_address0, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_address0, ap_CS_fsm_state25)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            x_buf_address0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            x_buf_address0 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_buf_address0 <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_address0;
        else 
            x_buf_address0 <= ap_const_lv4_0;
        end if; 
    end process;


    x_buf_ce0_assign_proc : process(ap_CS_fsm_state14, tmp_reg_339, tmp_1_reg_343, ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce0, grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_ce0, grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_ce0, ap_CS_fsm_state25, x_buf_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and (tmp_1_reg_343 = ap_const_lv1_1) and (tmp_reg_339 = ap_const_lv1_1))) then 
            x_buf_ce0 <= grp_lms_filter_Pipeline_VITIS_LOOP_49_3_fu_213_x_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            x_buf_ce0 <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_x_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_buf_ce0 <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce0;
        else 
            x_buf_ce0 <= x_buf_ce0_local;
        end if; 
    end process;


    x_buf_ce0_local_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            x_buf_ce0_local <= ap_const_logic_1;
        else 
            x_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    x_buf_ce1_assign_proc : process(ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_buf_ce1 <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_ce1;
        else 
            x_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    x_buf_d0_assign_proc : process(reg_235, ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_buf_d0 <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_d0;
        else 
            x_buf_d0 <= reg_235;
        end if; 
    end process;


    x_buf_we0_assign_proc : process(ap_CS_fsm_state2, grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_we0, x_buf_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_buf_we0 <= grp_lms_filter_Pipeline_VITIS_LOOP_33_1_fu_198_x_buf_we0;
        else 
            x_buf_we0 <= (x_buf_we0_out or ap_const_logic_0);
        end if; 
    end process;


    x_buf_we0_local_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            x_buf_we0_local <= ap_const_logic_1;
        else 
            x_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_we0_out <= x_buf_we0_local;

    x_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_104_p6, tmp_1_nbreadreq_fu_118_p6, x_in_TVALID_int_regslice)
    begin
        if (((tmp_1_nbreadreq_fu_118_p6 = ap_const_lv1_1) and (tmp_nbreadreq_fu_104_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_in_TDATA_blk_n <= x_in_TVALID_int_regslice;
        else 
            x_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_in_TREADY <= regslice_both_x_in_V_data_V_U_ack_in;

    x_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_predicate_op57_read_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_predicate_op57_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            x_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1_fu_310_p3 <= (xor_ln30_reg_378 & trunc_ln30_reg_362);
    xor_ln29_fu_266_p2 <= (bit_sel_fu_258_p3 xor ap_const_lv1_1);
    xor_ln30_fu_305_p2 <= (bit_sel1_reg_357 xor ap_const_lv1_1);
    xor_ln_fu_294_p3 <= (xor_ln29_reg_347 & trunc_ln29_reg_352);

    y_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state20, ap_CS_fsm_state21, y_out_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            y_out_TDATA_blk_n <= y_out_TREADY_int_regslice;
        else 
            y_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y_out_TDATA_int_regslice <= grp_lms_filter_Pipeline_VITIS_LOOP_41_2_fu_204_add255_out;
    y_out_TVALID <= regslice_both_y_out_V_data_V_U_vld_out;

    y_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state20, ap_block_state20)
    begin
        if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            y_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
