// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lms_filter_lms_filter,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=46.744000,HLS_SYN_LAT=31,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1354,HLS_SYN_LUT=2127,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module lms_filter (
        ap_clk,
        ap_rst_n,
        x_in_TDATA,
        x_in_TVALID,
        x_in_TREADY,
        x_in_TKEEP,
        x_in_TSTRB,
        x_in_TLAST,
        d_in_TDATA,
        d_in_TVALID,
        d_in_TREADY,
        d_in_TKEEP,
        d_in_TSTRB,
        d_in_TLAST,
        e_out_TDATA,
        e_out_TVALID,
        e_out_TREADY,
        e_out_TKEEP,
        e_out_TSTRB,
        e_out_TLAST
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst_n;
input  [7:0] x_in_TDATA;
input   x_in_TVALID;
output   x_in_TREADY;
input  [0:0] x_in_TKEEP;
input  [0:0] x_in_TSTRB;
input  [0:0] x_in_TLAST;
input  [7:0] d_in_TDATA;
input   d_in_TVALID;
output   d_in_TREADY;
input  [0:0] d_in_TKEEP;
input  [0:0] d_in_TSTRB;
input  [0:0] d_in_TLAST;
output  [31:0] e_out_TDATA;
output   e_out_TVALID;
input   e_out_TREADY;
output  [3:0] e_out_TKEEP;
output  [3:0] e_out_TSTRB;
output  [0:0] e_out_TLAST;

 reg    ap_rst_n_inv;
reg   [3:0] x_buf_address0;
reg    x_buf_ce0;
reg    x_buf_we0;
reg   [31:0] x_buf_d0;
wire   [31:0] x_buf_q0;
reg    x_buf_ce1;
wire   [31:0] x_buf_q1;
reg   [3:0] weights_address0;
reg    weights_ce0;
reg    weights_we0;
wire   [31:0] weights_q0;
reg    weights_ce1;
wire   [31:0] weights_q1;
reg    x_in_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_nbreadreq_fu_94_p6;
wire   [0:0] tmp_1_nbreadreq_fu_108_p6;
reg    d_in_TDATA_blk_n;
reg    e_out_TDATA_blk_n;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [31:0] grp_fu_198_p2;
reg   [31:0] reg_207;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state23;
reg   [0:0] tmp_reg_307;
reg   [0:0] tmp_1_reg_311;
wire   [0:0] xor_ln28_fu_238_p2;
reg   [0:0] xor_ln28_reg_315;
wire   [6:0] trunc_ln28_fu_244_p1;
reg   [6:0] trunc_ln28_reg_320;
reg   [0:0] bit_sel1_reg_325;
wire   [6:0] trunc_ln29_fu_256_p1;
reg   [6:0] trunc_ln29_reg_330;
wire   [0:0] or_ln59_fu_260_p2;
reg   [0:0] or_ln59_reg_335;
wire  signed [31:0] sext_ln28_fu_272_p1;
wire    ap_CS_fsm_state2;
wire   [0:0] xor_ln29_fu_277_p2;
reg   [0:0] xor_ln29_reg_345;
wire    ap_CS_fsm_state4;
wire  signed [31:0] sext_ln29_fu_288_p1;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_204_p1;
reg   [31:0] conv3_reg_355;
wire    ap_CS_fsm_state7;
reg   [31:0] conv8_reg_360;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_194_p2;
reg   [31:0] e_reg_368;
wire    ap_CS_fsm_state19;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_done;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_idle;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_ready;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_we0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_d0;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address1;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce1;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_done;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_idle;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_ready;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_y_out;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_y_out_ap_vld;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_address0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_ce0;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_address0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_ce0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din1;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_ce;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_done;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_idle;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_ready;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_address0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_ce0;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce0;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_we0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_d0;
wire   [3:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address1;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce1;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din1;
wire   [0:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_opcode;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_ce;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din0;
wire   [31:0] grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din1;
wire    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_ce;
reg    grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg;
reg    ap_predicate_op51_read_state1;
reg    ap_predicate_op54_read_state1;
reg    ap_block_state1_ignore_call6;
wire    x_buf_we0_out;
reg    grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg;
wire    ap_CS_fsm_state13;
reg    grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state15;
reg    ap_block_state1;
reg    x_buf_we0_local;
wire    ap_CS_fsm_state12;
reg    x_buf_ce0_local;
reg   [31:0] grp_fu_194_p0;
reg   [31:0] grp_fu_194_p1;
reg   [31:0] grp_fu_198_p0;
reg   [31:0] grp_fu_198_p1;
wire    ap_CS_fsm_state8;
reg  signed [31:0] grp_fu_204_p0;
wire   [0:0] bit_sel_fu_230_p3;
wire   [7:0] xor_ln_fu_266_p3;
wire   [7:0] xor_ln1_fu_282_p3;
reg   [1:0] grp_fu_194_opcode;
reg    grp_fu_194_ce;
reg    grp_fu_198_ce;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state22;
reg    grp_fu_204_ce;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_379_p2;
reg   [31:0] grp_fu_379_p0;
reg   [31:0] grp_fu_379_p1;
reg    grp_fu_379_ce;
reg   [24:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    regslice_both_e_out_V_data_V_U_apdone_blk;
reg    ap_predicate_op107_call_state25;
reg    ap_block_state25_on_subcall_done;
wire    regslice_both_x_in_V_data_V_U_apdone_blk;
wire   [7:0] x_in_TDATA_int_regslice;
wire    x_in_TVALID_int_regslice;
reg    x_in_TREADY_int_regslice;
wire    regslice_both_x_in_V_data_V_U_ack_in;
wire    regslice_both_x_in_V_keep_V_U_apdone_blk;
wire   [0:0] x_in_TKEEP_int_regslice;
wire    regslice_both_x_in_V_keep_V_U_vld_out;
wire    regslice_both_x_in_V_keep_V_U_ack_in;
wire    regslice_both_x_in_V_strb_V_U_apdone_blk;
wire   [0:0] x_in_TSTRB_int_regslice;
wire    regslice_both_x_in_V_strb_V_U_vld_out;
wire    regslice_both_x_in_V_strb_V_U_ack_in;
wire    regslice_both_x_in_V_last_V_U_apdone_blk;
wire   [0:0] x_in_TLAST_int_regslice;
wire    regslice_both_x_in_V_last_V_U_vld_out;
wire    regslice_both_x_in_V_last_V_U_ack_in;
wire    regslice_both_d_in_V_data_V_U_apdone_blk;
wire   [7:0] d_in_TDATA_int_regslice;
wire    d_in_TVALID_int_regslice;
reg    d_in_TREADY_int_regslice;
wire    regslice_both_d_in_V_data_V_U_ack_in;
wire    regslice_both_d_in_V_keep_V_U_apdone_blk;
wire   [0:0] d_in_TKEEP_int_regslice;
wire    regslice_both_d_in_V_keep_V_U_vld_out;
wire    regslice_both_d_in_V_keep_V_U_ack_in;
wire    regslice_both_d_in_V_strb_V_U_apdone_blk;
wire   [0:0] d_in_TSTRB_int_regslice;
wire    regslice_both_d_in_V_strb_V_U_vld_out;
wire    regslice_both_d_in_V_strb_V_U_ack_in;
wire    regslice_both_d_in_V_last_V_U_apdone_blk;
wire   [0:0] d_in_TLAST_int_regslice;
wire    regslice_both_d_in_V_last_V_U_vld_out;
wire    regslice_both_d_in_V_last_V_U_ack_in;
wire   [31:0] e_out_TDATA_int_regslice;
reg    e_out_TVALID_int_regslice;
wire    e_out_TREADY_int_regslice;
wire    regslice_both_e_out_V_data_V_U_vld_out;
wire    regslice_both_e_out_V_keep_V_U_apdone_blk;
wire    regslice_both_e_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_e_out_V_keep_V_U_vld_out;
wire    regslice_both_e_out_V_strb_V_U_apdone_blk;
wire    regslice_both_e_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_e_out_V_strb_V_U_vld_out;
wire    regslice_both_e_out_V_last_V_U_apdone_blk;
wire    regslice_both_e_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_e_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg = 1'b0;
#0 grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg = 1'b0;
#0 grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg = 1'b0;
end

lms_filter_x_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_buf_address0),
    .ce0(x_buf_ce0),
    .we0(x_buf_we0),
    .d0(x_buf_d0),
    .q0(x_buf_q0),
    .address1(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address1),
    .ce1(x_buf_ce1),
    .q1(x_buf_q1)
);

lms_filter_x_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
weights_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(weights_address0),
    .ce0(weights_ce0),
    .we0(weights_we0),
    .d0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_d0),
    .q0(weights_q0),
    .address1(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address1),
    .ce1(weights_ce1),
    .q1(weights_q1)
);

lms_filter_lms_filter_Pipeline_VITIS_LOOP_32_1 grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start),
    .ap_done(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_done),
    .ap_idle(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_idle),
    .ap_ready(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_ready),
    .x_buf_address0(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address0),
    .x_buf_ce0(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce0),
    .x_buf_we0(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_we0),
    .x_buf_d0(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_d0),
    .x_buf_address1(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address1),
    .x_buf_ce1(grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce1),
    .x_buf_q1(x_buf_q1)
);

lms_filter_lms_filter_Pipeline_VITIS_LOOP_40_2 grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start),
    .ap_done(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_done),
    .ap_idle(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_idle),
    .ap_ready(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_ready),
    .y_out(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_y_out),
    .y_out_ap_vld(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_y_out_ap_vld),
    .weights_address0(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_address0),
    .weights_ce0(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_ce0),
    .weights_q0(weights_q0),
    .x_buf_address0(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_address0),
    .x_buf_ce0(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_ce0),
    .x_buf_q0(x_buf_q0),
    .grp_fu_379_p_din0(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din0),
    .grp_fu_379_p_din1(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din1),
    .grp_fu_379_p_dout0(grp_fu_379_p2),
    .grp_fu_379_p_ce(grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_ce)
);

lms_filter_lms_filter_Pipeline_VITIS_LOOP_48_3 grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start),
    .ap_done(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_done),
    .ap_idle(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_idle),
    .ap_ready(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_ready),
    .mul1(reg_207),
    .x_buf_address0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_address0),
    .x_buf_ce0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_ce0),
    .x_buf_q0(x_buf_q0),
    .weights_address0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address0),
    .weights_ce0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce0),
    .weights_we0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_we0),
    .weights_d0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_d0),
    .weights_address1(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address1),
    .weights_ce1(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce1),
    .weights_q1(weights_q1),
    .grp_fu_194_p_din0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din0),
    .grp_fu_194_p_din1(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din1),
    .grp_fu_194_p_opcode(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_opcode),
    .grp_fu_194_p_dout0(grp_fu_194_p2),
    .grp_fu_194_p_ce(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_ce),
    .grp_fu_379_p_din0(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din0),
    .grp_fu_379_p_din1(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din1),
    .grp_fu_379_p_dout0(grp_fu_379_p2),
    .grp_fu_379_p_ce(grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_ce)
);

lms_filter_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_194_p0),
    .din1(grp_fu_194_p1),
    .opcode(grp_fu_194_opcode),
    .ce(grp_fu_194_ce),
    .dout(grp_fu_194_p2)
);

lms_filter_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_198_p0),
    .din1(grp_fu_198_p1),
    .ce(grp_fu_198_ce),
    .dout(grp_fu_198_p2)
);

lms_filter_sitofp_32s_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_6_no_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_204_p0),
    .ce(grp_fu_204_ce),
    .dout(grp_fu_204_p1)
);

lms_filter_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_379_p0),
    .din1(grp_fu_379_p1),
    .ce(grp_fu_379_ce),
    .dout(grp_fu_379_p2)
);

lms_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_x_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_in_TDATA),
    .vld_in(x_in_TVALID),
    .ack_in(regslice_both_x_in_V_data_V_U_ack_in),
    .data_out(x_in_TDATA_int_regslice),
    .vld_out(x_in_TVALID_int_regslice),
    .ack_out(x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_in_V_data_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_in_TKEEP),
    .vld_in(x_in_TVALID),
    .ack_in(regslice_both_x_in_V_keep_V_U_ack_in),
    .data_out(x_in_TKEEP_int_regslice),
    .vld_out(regslice_both_x_in_V_keep_V_U_vld_out),
    .ack_out(x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_in_V_keep_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_in_TSTRB),
    .vld_in(x_in_TVALID),
    .ack_in(regslice_both_x_in_V_strb_V_U_ack_in),
    .data_out(x_in_TSTRB_int_regslice),
    .vld_out(regslice_both_x_in_V_strb_V_U_vld_out),
    .ack_out(x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_in_V_strb_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_in_TLAST),
    .vld_in(x_in_TVALID),
    .ack_in(regslice_both_x_in_V_last_V_U_ack_in),
    .data_out(x_in_TLAST_int_regslice),
    .vld_out(regslice_both_x_in_V_last_V_U_vld_out),
    .ack_out(x_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_in_V_last_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 8 ))
regslice_both_d_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TDATA),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_data_V_U_ack_in),
    .data_out(d_in_TDATA_int_regslice),
    .vld_out(d_in_TVALID_int_regslice),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_data_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_d_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TKEEP),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_keep_V_U_ack_in),
    .data_out(d_in_TKEEP_int_regslice),
    .vld_out(regslice_both_d_in_V_keep_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_keep_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_d_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TSTRB),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_strb_V_U_ack_in),
    .data_out(d_in_TSTRB_int_regslice),
    .vld_out(regslice_both_d_in_V_strb_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_strb_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_d_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TLAST),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_last_V_U_ack_in),
    .data_out(d_in_TLAST_int_regslice),
    .vld_out(regslice_both_d_in_V_last_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_last_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_e_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(e_out_TDATA_int_regslice),
    .vld_in(e_out_TVALID_int_regslice),
    .ack_in(e_out_TREADY_int_regslice),
    .data_out(e_out_TDATA),
    .vld_out(regslice_both_e_out_V_data_V_U_vld_out),
    .ack_out(e_out_TREADY),
    .apdone_blk(regslice_both_e_out_V_data_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_e_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(e_out_TVALID_int_regslice),
    .ack_in(regslice_both_e_out_V_keep_V_U_ack_in_dummy),
    .data_out(e_out_TKEEP),
    .vld_out(regslice_both_e_out_V_keep_V_U_vld_out),
    .ack_out(e_out_TREADY),
    .apdone_blk(regslice_both_e_out_V_keep_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 4 ))
regslice_both_e_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(e_out_TVALID_int_regslice),
    .ack_in(regslice_both_e_out_V_strb_V_U_ack_in_dummy),
    .data_out(e_out_TSTRB),
    .vld_out(regslice_both_e_out_V_strb_V_U_vld_out),
    .ack_out(e_out_TREADY),
    .apdone_blk(regslice_both_e_out_V_strb_V_U_apdone_blk)
);

lms_filter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_e_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(or_ln59_reg_335),
    .vld_in(e_out_TVALID_int_regslice),
    .ack_in(regslice_both_e_out_V_last_V_U_ack_in_dummy),
    .data_out(e_out_TLAST),
    .vld_out(regslice_both_e_out_V_last_V_U_vld_out),
    .ack_out(e_out_TREADY),
    .apdone_blk(regslice_both_e_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1) & (1'b0 == ap_block_state1_ignore_call6) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_ready == 1'b1)) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_ready == 1'b1)) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state24)) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_ready == 1'b1)) begin
            grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bit_sel1_reg_325 <= d_in_TDATA_int_regslice[8'd7];
        or_ln59_reg_335 <= or_ln59_fu_260_p2;
        tmp_1_reg_311 <= tmp_1_nbreadreq_fu_108_p6;
        tmp_reg_307 <= tmp_nbreadreq_fu_94_p6;
        trunc_ln28_reg_320 <= trunc_ln28_fu_244_p1;
        trunc_ln29_reg_330 <= trunc_ln29_fu_256_p1;
        xor_ln28_reg_315 <= xor_ln28_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        conv3_reg_355 <= grp_fu_204_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        conv8_reg_360 <= grp_fu_204_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        e_reg_368 <= grp_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_207 <= grp_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        xor_ln29_reg_345 <= xor_ln29_fu_277_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((e_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((e_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state25_on_subcall_done) | (regslice_both_e_out_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        d_in_TDATA_blk_n = d_in_TVALID_int_regslice;
    end else begin
        d_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (ap_predicate_op54_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        d_in_TREADY_int_regslice = 1'b1;
    end else begin
        d_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        e_out_TDATA_blk_n = e_out_TREADY_int_regslice;
    end else begin
        e_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((e_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        e_out_TVALID_int_regslice = 1'b1;
    end else begin
        e_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_194_ce = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_ce;
    end else begin
        grp_fu_194_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_194_opcode = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_194_opcode = 2'd1;
    end else begin
        grp_fu_194_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_194_p0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_194_p0 = reg_207;
    end else begin
        grp_fu_194_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_194_p1 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_194_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_194_p1 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_y_out;
    end else begin
        grp_fu_194_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state11) | ((e_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((e_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state14) & (grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_done == 1'b1)))) begin
        grp_fu_198_ce = 1'b1;
    end else begin
        grp_fu_198_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_198_p0 = e_reg_368;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_198_p0 = conv8_reg_360;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_198_p0 = conv3_reg_355;
    end else begin
        grp_fu_198_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_198_p1 = 32'd1008981770;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state11))) begin
        grp_fu_198_p1 = 32'd1006632960;
    end else begin
        grp_fu_198_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state2) & (grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_done == 1'b1)))) begin
        grp_fu_204_ce = 1'b1;
    end else begin
        grp_fu_204_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_204_p0 = sext_ln29_fu_288_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_204_p0 = sext_ln28_fu_272_p1;
    end else begin
        grp_fu_204_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_379_ce = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_379_ce = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_ce;
    end else begin
        grp_fu_379_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_379_p0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_379_p0 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din0;
    end else begin
        grp_fu_379_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_379_p1 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_grp_fu_379_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_379_p1 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_grp_fu_379_p_din1;
    end else begin
        grp_fu_379_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        weights_address0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        weights_address0 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_address0;
    end else begin
        weights_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        weights_ce0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        weights_ce0 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_weights_ce0;
    end else begin
        weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        weights_ce1 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_ce1;
    end else begin
        weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        weights_we0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_weights_we0;
    end else begin
        weights_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        x_buf_address0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_buf_address0 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_buf_address0 = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_address0;
    end else begin
        x_buf_address0 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1))) begin
        x_buf_ce0 = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_x_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_buf_ce0 = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_x_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_buf_ce0 = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce0;
    end else begin
        x_buf_ce0 = x_buf_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_buf_ce0_local = 1'b1;
    end else begin
        x_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_buf_ce1 = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_ce1;
    end else begin
        x_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_buf_d0 = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_d0;
    end else begin
        x_buf_d0 = reg_207;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_buf_we0 = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_x_buf_we0;
    end else begin
        x_buf_we0 = (x_buf_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        x_buf_we0_local = 1'b1;
    end else begin
        x_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_in_TDATA_blk_n = x_in_TVALID_int_regslice;
    end else begin
        x_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (ap_predicate_op51_read_state1 == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_in_TREADY_int_regslice = 1'b1;
    end else begin
        x_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1) & ((tmp_1_nbreadreq_fu_108_p6 == 1'd0) | (tmp_nbreadreq_fu_94_p6 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((e_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((e_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if ((~((1'b1 == ap_block_state25_on_subcall_done) | (regslice_both_e_out_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = (((d_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op54_read_state1 == 1'b1)) | ((x_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op51_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_ignore_call6 = (((d_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op54_read_state1 == 1'b1)) | ((x_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op51_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state25_on_subcall_done = ((ap_predicate_op107_call_state25 == 1'b1) & (grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op107_call_state25 = ((tmp_1_reg_311 == 1'd1) & (tmp_reg_307 == 1'd1));
end

always @ (*) begin
    ap_predicate_op51_read_state1 = ((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1));
end

always @ (*) begin
    ap_predicate_op54_read_state1 = ((tmp_1_nbreadreq_fu_108_p6 == 1'd1) & (tmp_nbreadreq_fu_94_p6 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bit_sel_fu_230_p3 = x_in_TDATA_int_regslice[8'd7];

assign d_in_TREADY = regslice_both_d_in_V_data_V_U_ack_in;

assign e_out_TDATA_int_regslice = e_reg_368;

assign e_out_TVALID = regslice_both_e_out_V_data_V_U_vld_out;

assign grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start = grp_lms_filter_Pipeline_VITIS_LOOP_32_1_fu_170_ap_start_reg;

assign grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start = grp_lms_filter_Pipeline_VITIS_LOOP_40_2_fu_176_ap_start_reg;

assign grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start = grp_lms_filter_Pipeline_VITIS_LOOP_48_3_fu_185_ap_start_reg;

assign or_ln59_fu_260_p2 = (x_in_TLAST_int_regslice | d_in_TLAST_int_regslice);

assign sext_ln28_fu_272_p1 = $signed(xor_ln_fu_266_p3);

assign sext_ln29_fu_288_p1 = $signed(xor_ln1_fu_282_p3);

assign tmp_1_nbreadreq_fu_108_p6 = d_in_TVALID_int_regslice;

assign tmp_nbreadreq_fu_94_p6 = x_in_TVALID_int_regslice;

assign trunc_ln28_fu_244_p1 = x_in_TDATA_int_regslice[6:0];

assign trunc_ln29_fu_256_p1 = d_in_TDATA_int_regslice[6:0];

assign x_buf_we0_out = x_buf_we0_local;

assign x_in_TREADY = regslice_both_x_in_V_data_V_U_ack_in;

assign xor_ln1_fu_282_p3 = {{xor_ln29_reg_345}, {trunc_ln29_reg_330}};

assign xor_ln28_fu_238_p2 = (bit_sel_fu_230_p3 ^ 1'd1);

assign xor_ln29_fu_277_p2 = (bit_sel1_reg_325 ^ 1'd1);

assign xor_ln_fu_266_p3 = {{xor_ln28_reg_315}, {trunc_ln28_reg_320}};

endmodule //lms_filter
